% Makefile

x = 0;


% path = '../eclipse_ubuntu/kvamme_qp/src/';
%addpath('../matlab')
addpath('/opt/gurobi563/linux64/matlab');
%addpath('./');

%mex -O -v CC=gcc LD=gcc COPTIMFLAGS='-O3 -DNDEBUG' CFLAGS="\$CFLAGS -std=c99  -I./include ...
if x == 0
    %mex -O  CFLAGS="\$CFLAGS -std=c99  -I./include -O3"...
    mex -O CC=gcc LD=gcc COPTIMFLAGS='-O3 -DNDEBUG'...
        CFLAGS="\$CFLAGS -std=c99  -I../eclipse_luna_ubuntu14/qp-toolbox/include"...
        /home/sverre/Dropbox/NTNU/Master/code/thesis/MEX/main.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/print.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/fgm.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/gdm.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/math_functions.c... 
        ../eclipse_luna_ubuntu14/qp-toolbox/src/dgm.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/general_functions.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/dfgm.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/alm.c...
         ../eclipse_luna_ubuntu14/qp-toolbox/src/falm.c
elseif x == 1  
    % debug
    mex -O CC=gcc LD=gcc...
        CFLAGS="\$CFLAGS -std=c99 -DSDEBUG -I../eclipse_luna_ubuntu14/qp-toolbox/include"...
        main.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/print.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/FGM.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/GDM.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/math_functions.c... 
        ../eclipse_luna_ubuntu14/qp-toolbox/src/DGM.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/general_functions.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/DFGM.c
elseif x == 2  
    % simple debug
    mex -O CC=gcc LD=gcc ...
        CFLAGS="\$CFLAGS -std=c99 -DSDEBUG -DDEBUG -DDEBUG2...
        -I../eclipse_luna_ubuntu14/qp-toolbox/include"...
        main.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/print.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/FGM.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/GDM.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/math_functions.c... 
        ../eclipse_luna_ubuntu14/qp-toolbox/src/DGM.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/general_functions.c...
        ../eclipse_luna_ubuntu14/qp-toolbox/src/DFGM.c
end


    
% Compile with: mex -O CFLAGS="\$CFLAGS -std=c99" main.c
% Run with e.g.: [a,b] = main(2,3)
